/**
 * Users action types
 */

export const LOGIN_FIELD_HAS_CHANGED = 'LOGIN_FIELD_HAS_CHANGED';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const REGISTRATION_FIELD_HAS_CHANGED = 'REGISTRATION_FIELD_HAS_CHANGED';
export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAILURE = 'CREATE_NEW_USER_FAILURE';


/**
 * Sets action types
 */

export const SET_CREATE_TITLE_HAS_CHANGED = 'SET_CREATE_TITLE_HAS_CHANGED';
export const SET_CREATE_REQUEST_WAS_MADE = 'SET_CREATE_REQUEST_WAS_MADE';
export const SET_CREATE_SUCCESS = 'SET_CREATE_SUCCESS';
export const SET_HAS_BEEN_DELETED = 'SET_HAS_BEEN_DELETED';
export const SET_MODIFICATION_REQUEST = 'SET_MODIFICATION_REQUEST';
export const SET_MODIFICATION_SUBMIT = 'SET_MODIFICATION_SUBMIT';

/**
 * Set flashcards
 */
export const SET_FLASHCARD_ADD = 'SET_FLASHCARD_ADD';
export const SET_FLASHCARD_REMOVE = 'SET_FLASHCARD_REMOVE';
export const SET_FLASHCARD_HAS_CHANGED = 'SET_FLASHCARD_HAS_CHANGED';

